<!--METADATA TYPE="typelib" UUID="CD000000-8B95-11D1-82DB-00C04FB1625D" NAME="CDO for Windows Library" -->
<% 

Response.AddHeader "Pragma", "No-Store"
Response.AddHeader "cache-control", "no-store, private, must-revalidate"
Response.Expires = -1
Response.ExpiresAbsolute = DateAdd("Y", -10, ServerToEST(Now()))
Response.CacheControl = "no-store, private, must-revalidate"

If Not Request.Cookies("DivisionIdsAccess")("PurchaseOrders") <> "0" Then Response.Redirect("../Portal/AccessDenied.asp")

%>
<!--#include virtual="/System/ssi_Functions.asp"-->
<!--#include virtual="/Clients/SalesEngine/ssi_Security.inc"-->
<!--#include virtual="/System/ssi_dbConn_open.inc"-->
<!--#include virtual="/System/ssi_Dates.inc"-->
<%

strCode = Request.Cookies("UserSettings")("Code")
strProject = Request("Project")
lngContactId = Request("ContactId")
lngDivisionId = Request("DivisionId")
boolGST = CBool(Request("GST"))
lngPOStatusId = CInt(Request("POStatusId"))
lngPOPaymentTypeId = Request("POPaymentTypeId")
strTerms = Replace(Trim(Request("Terms")), "'", "''")
strDateRequired = Request("DateRequired")
lngDeliverToLocationId = Request("DeliverToLocationId")
strDeliverToLocation = Trim(Replace(Request("DeliverToLocation"),"'","''"))
strProject = Trim(Replace(Trim(Request("Project")), "'", "''"))
strIntroText = Trim(Replace(Trim(Request("IntroText")), "'", "''"))
strInternalNotes = Trim(Replace(Trim(Request("InternalNotes")), "'", "''"))
strPriceExTotal = Trim(Request("PriceExTotal"))
strPriceGSTTotal = Trim(Request("PriceGSTTotal"))
strPriceIncTotal = Trim(Request("PriceIncTotal"))
lngRFQid = CLng(Request("RFQid"))
lngQid = CLng(Request("Qid"))

If Not boolGST Then
	strPriceGSTTotal = "0"
	strPriceIncTotal = strPriceExTotal
End If

intItemLinesVal = CInt(Request.Form("ItemLinesVal"))

If lngContactId <> "" Then InsertFor(lngContactId)

Function InsertFor(lngContactId)
	sql = "Insert Into PurchaseOrders (Code, Project, ContactId, DivisionId, PODate, POStatusId, GST, POPaymentTypeId, Terms, DateRequired, DeliverToLocationId, DeliverToLocation, IntroText, InternalNotes, PriceExTotal, PriceGSTTotal, PriceIncTotal, RFQid, Qid) Values ('" & Request.Cookies("UserSettings")("Code") & "', '" & strProject & "', " & lngContactId & ", " & lngDivisionId & ", '" & ServerToEST(Now()) & "', " & lngPOStatusId & ", " & boolGST & ", " & lngPOPaymentTypeId & ", '" & strTerms & "', '" & strDateRequired & "', " & lngDeliverToLocationId & ", '" & strDeliverToLocation & "', '" & strIntroText & "', '" & strInternalNotes & "', " & strPriceExTotal & ", " & strPriceGSTTotal & ", " & strPriceIncTotal & ", " & lngRFQid & ", " & lngQid & ")"
	dbConn.Execute(sql)

	Set rsNew = Server.CreateObject("ADODB.RecordSet")
	sql = "Select @@IDENTITY As POid"
	Set rsNew = dbConn.Execute(sql)

	lngPOid = rsNew("POid")

	rsNew.Close
	Set rsNew = Nothing

	boolCapEx = False

	' Items
	For i = 2 To intItemLinesVal
		If IsNumeric(Request.Form("Quantity" & i)) And Trim(Request.Form("Item" & i)) <> "" Then
			lngQuantity = Request.Form("Quantity" & i)
			strItem = Replace(Request.Form("Item" & i),"'","''")
			strPriceEx = Request.Form("PriceEx" & i)
			strPriceExSubTotal = Request.Form("PriceExSubTotal" & i)
			lngPOProductTypeId = Request.Form("POProductTypeId" & i)
			intPartCodeId = Request.Form("PartCodeId" & i)

			' Check if Cap Ex. or not
			sql = "Select CapEx From PurchaseOrderProductTypes Where POProductTypeId = " & lngPOProductTypeId
			Set rsCapEx = dbConn.Execute(sql)
			If rsCapEx("CapEx") Then boolCapEx = True

			sql = "Insert Into PurchaseOrderContents (POid, PartCodeId, Quantity, Description, PriceEx, PriceExSubTotal, POProductTypeId) Values (" & lngPOid & ", " & intPartCodeId & ", " & lngQuantity & ", '" & strItem & "', " & strPriceEx & ", " & strPriceExSubTotal & ", " & lngPOProductTypeId & ")"
			dbConn.Execute(sql)
		End If
	Next
	
	If boolCapEx Then
		sql = "Update PurchaseOrders Set HasCapEx = true Where POid = " & lngPOid
		dbConn.Execute(sql)
	End If

	If lngRFQid > 0 Then
		' Audit trail
		sql = "Insert Into PurchaseOrderAudit (POid, Code, Action, DateEntered) Values (" & lngPOid & ", '" & Request.Cookies("UserSettings")("Code") & "', 'Generated by RFQ # " & lngRFQid & "', '" & ServerToEST(Now()) & "')"
		dbConn.Execute(sql)
	End If

	' Audit trail
	sql = "Insert Into PurchaseOrderAudit (POid, Code, Action, DateEntered) Values (" & lngPOid & ", '" & Request.Cookies("UserSettings")("Code") & "', 'Created', '" & ServerToEST(Now()) & "')"
	dbConn.Execute(sql)

	If GetPOLastLineApprover(lngPOid, boolCapEx) = "Already approved"  Then
		sql = "Insert Into PurchaseOrderApproval (POid, Code) Values (" & lngPOid & ", '" & Request.Cookies("UserSettings")("Code") & "')"
		dbConn.Execute(sql)

		sql = "Update PurchaseOrders Set POStatusId = 3 Where POid = " & lngPOid
		dbConn.Execute(sql)

		' Audit trail
		sql = "Insert Into PurchaseOrderAudit (POid, Code, Action, DateEntered) Values (" & lngPOid & ", '" & Request.Cookies("UserSettings")("Code") & "', 'Approved', '" & ServerToEST(Now()) & "')"
		dbConn.Execute(sql)
	Else
		If lngPOStatusId = 2 Then
			' Approval Process
			strBodyText = "MyDesk " & Request.Cookies("ClientSettings")("PortalCompany") & " Alert : Purchase Order #" & lngPOid & " : Approved by " & Request.Cookies("UserSettings")("Name") & ". The next approver in the approval process is " & GetPONextLineApprover(lngPOid, boolCapEx) & "." & PurchaseOrderDetails_ForEmail(lngPOid)
			SendMail Request.Cookies("UserSettings")("Email"), GetPONextLineApprover_Email(lngPOid, boolCapEx), "MyDesk " & Request.Cookies("ClientSettings")("PortalCompany") & " Alert : Purchase Order #" & lngPOid & " : Waiting for your approval. Just approved by " & Request.Cookies("UserSettings")("Name"), strBodyText
		End If
	End If
End Function

%>
<!--#include virtual="/System/ssi_dbConn_close.inc"-->
<%

MyRedirect("Default.asp?DivisionId=" & lngDivisionId & "&Msg=Purchase+Order+added")

%>