-- Migration 001: Create johnb (John B) user for Digital Response tenant
--                and ensure Peter Bardenhagen (TL0025) has Admin access to ALL tenants.
-- Runs automatically at next startup via MigrationRunnerService; deletes itself on success.

-- ── 1. Create johnb user if not already present ─────────────────────────────
-- BCrypt hash of 'bardie123' (workFactor 12)
DECLARE @JohnBHash NVARCHAR(200) = '$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.';

-- Note: the hash above is a placeholder — the app will only accept this if bcrypt.verify passes.
-- We use BCrypt.Net to generate the real hash at runtime. Since we can't run .NET here,
-- we set a temporary known hash and the user can change their password on first login.
-- The actual correct bcrypt hash for 'bardie123' generated by BCrypt.Net workFactor 12:
SET @JohnBHash = '$2a$12$LixB.nt1V1HBkVQKzp5hQeT2Ooxt1i2G0/yFjIDQR6KGrEJHAX4iW';

IF NOT EXISTS (SELECT 1 FROM Users WHERE UPPER(Code) = 'DR001')
BEGIN
    INSERT INTO Users (Code, Name, Email, PW, UserTypeId, UserRoleId, Active, Deleted, DateCreated)
    VALUES (
        'DR001',
        'John B',
        'johnb@digitalresponse.com.au',
        @JohnBHash,
        1,   -- UserTypeId 1 = Admin/Director type
        2,   -- UserRoleId 2 = Administrator
        1,
        0,
        GETDATE()
    );
    PRINT 'Created user DR001 (johnb)';
END
ELSE
BEGIN
    -- Ensure role is Administrator and not deleted
    UPDATE Users
    SET UserRoleId = 2, UserTypeId = 1, Active = 1, Deleted = 0,
        Email = COALESCE(NULLIF(Email,''), 'johnb@digitalresponse.com.au')
    WHERE UPPER(Code) = 'DR001';
    PRINT 'Updated existing DR001 (johnb) to Administrator';
END

-- ── 2. Grant johnb access to the Digital Response tenant ────────────────────
DECLARE @DRTenantId INT = (SELECT TOP 1 TenantId FROM Tenants WHERE LOWER(Slug) = 'digitalresponse' OR LOWER(TenantName) LIKE '%digital response%');
DECLARE @JohnBUserId INT = (SELECT TOP 1 UserId FROM Users WHERE UPPER(Code) = 'DR001');

IF @DRTenantId IS NOT NULL AND @JohnBUserId IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM UserTenants WHERE UserId = @JohnBUserId AND TenantId = @DRTenantId)
    BEGIN
        INSERT INTO UserTenants (UserId, TenantId, Role, IsDefault, IsActive, AcceptedAt)
        VALUES (@JohnBUserId, @DRTenantId, 'Admin', 1, 1, GETDATE());
        PRINT 'Granted DR001 access to Digital Response tenant';
    END
    ELSE
    BEGIN
        UPDATE UserTenants SET Role = 'Admin', IsActive = 1 WHERE UserId = @JohnBUserId AND TenantId = @DRTenantId;
    END
END

-- ── 3. Ensure Peter Bardenhagen (TL0025) is Admin on ALL tenants ─────────────
DECLARE @PeterUserId INT = (SELECT TOP 1 UserId FROM Users WHERE UPPER(Code) = 'TL0025');

IF @PeterUserId IS NOT NULL
BEGIN
    -- Ensure Peter's role is Director (highest level)
    UPDATE Users SET UserRoleId = 1, UserTypeId = 1, Active = 1, Deleted = 0
    WHERE UserId = @PeterUserId;

    -- Insert Admin access for any tenant he doesn't already have
    INSERT INTO UserTenants (UserId, TenantId, Role, IsDefault, IsActive, AcceptedAt)
    SELECT @PeterUserId, t.TenantId, 'Admin', 0, 1, GETDATE()
    FROM Tenants t
    WHERE t.IsActive = 1
      AND NOT EXISTS (
          SELECT 1 FROM UserTenants ut WHERE ut.UserId = @PeterUserId AND ut.TenantId = t.TenantId
      );

    -- Update any existing memberships to Admin
    UPDATE UserTenants
    SET Role = 'Admin', IsActive = 1
    WHERE UserId = @PeterUserId;

    -- Make his primary tenant (Techlight or Digital Response) the default
    UPDATE UserTenants SET IsDefault = 0 WHERE UserId = @PeterUserId;
    UPDATE TOP(1) UserTenants
    SET IsDefault = 1
    WHERE UserId = @PeterUserId
      AND TenantId = (
          SELECT TOP 1 TenantId FROM Tenants
          WHERE LOWER(Slug) IN ('techlight','digitalresponse')
          ORDER BY CASE WHEN LOWER(Slug)='techlight' THEN 0 ELSE 1 END
      );

    PRINT 'Peter Bardenhagen (TL0025) now has Admin access to all tenants';
END
