global using System.Data;
global using System.Net.Http.Json;
global using Microsoft.AspNetCore.OpenApi;
global using Microsoft.OpenApi.Models;
global using SixLabors.ImageSharp;
global using SixLabors.ImageSharp.Processing;
global using SixLabors.ImageSharp.Formats;
global using SixLabors.ImageSharp.PixelFormats;
global using MyDesk.Shared.Services;
global using Path = System.IO.Path;
global using NotificationService = MyDesk.Web.Services.NotificationService;
